from selenium.webdriver.common.by import By

#Ticket_locator=(By.XPATH,"(//span[text()='Dummy ticket for visa application - $200 '])")
first_name_locator = (By.XPATH, "(//input[@id='firstname'])[1]")
last_name_locator = (By.XPATH, "(//input[@id='firstname'])[2]")
DOB_locator=(By.XPATH,"//input[@id='birthday']")
Trip_locator=(By.ID,"roundtrip")
Msg_locator=(By.ID,"whatsapp")
Billingname_locator=(By.ID,"billing_name")
phone_locator=(By.XPATH,"//input[@id='billing_phone']")
male_locator = (By.ID, "male")
female_locator = (By.ID, "female")
fromcity_locator = (By.ID, "fromcity")
destination_locator = (By.ID, "destcity")
phone_locator=(By.ID,"billing_phone")
email_locator=(By.ID,"billing_email")
street_locator=(By.ID,"billing_address")
post_locator=(By.ID,"postcode")
prefecture_locator=(By.ID,"Prefecture")
S_address_locator=(By.ID,"street_address1")
S1_address_locator=(By.ID,"street_address2")
#place_locator=(By.XPATH,"(//td[text()='Mumbai']//preceding-sibling::td[text()='6001'])")
DOB_locator=(By.ID, "visadate")
checkbox_locator=(By.XPATH,"(//input[@type='checkbox'])[1]")
country_dropdown_locator = (By.ID, "billing_country")
header_locator=