from selenium.webdriver.common.by import By

loct_choose_option = (By.XPATH, "//span[text()='Dummy return ticket - $300 ']//preceding-sibling::input")
loct_first_name = (By.XPATH, "(//input[@id='firstname'])[1]")
loct_last_name = (By.XPATH, "(//input[@id='firstname'])[2]")
loct_female = (By.ID, "female")
loct_number_passangers = (By.ID, "admorepass")
loct_trip = (By.ID, "roundtrip")
fromcity_locator = (By.ID, "fromcity")
destination_locator = (By.ID, "destcity")
loct_dummy_ticket = (By.XPATH,"//input[@type='radio'][@id='whatsapp']")
loct_billing_name = (By.ID, "billing_name")
loct_billing_phone = (By.ID, "billing_phone")
loct_billing_email = (By.ID, "billing_email")
loct_billing_address = (By.ID, "billing_address")
loct_postcode = (By.ID, "postcode")
loct_Prefecture = (By.ID, "Prefecture")
loct_street_address1 = (By.ID, "street_address1")
loct_street_address2 = (By.ID, "street_address2")
loct_Most_Visited_Cities = (By.XPATH, "//td[text()='Delhi']//preceding-sibling::td//input")
loct_birthday = (By.NAME, "birthday")
loct_Country = (By.ID, "billing_country")
loct_Departure_Date = (By.ID, "departdate")
loct_Return_Date = (By.ID, "returndate")
loct_visa_Date = (By.ID, "visadate")