Firstname = "Neha"
LastName = "Kumari"
DOB = "08/04/2024"
from_city = "Bengaluru"
destination_city = "Delhi"
Visa_interview_date = "09/04/2024"

#Bill details
Billing_name = "Peeyush"
Billing_phone = "987654321"
Email_id = "peeyush@gmail.com"
Street_Address = "Heenur Main road"
Country = "India"
Postal = "5600001"
prefecture = "ABC"
Street_add1 = "Power"
Street_add2 = "Grateful"